### ISSUE TITLE
Setup Zammad using Docker

### ISSUE THREAD

**Issue by iiiancampbell** [iiiancampbell/teamXenon#12]
Create a directory for Zammad:
`mkdir ~/zammad && cd ~/zammad`

Download the official docker-compose.yml:
`curl -O https://raw.githubusercontent.com/zammad/zammad-docker-compose/main/docker-compose.yml`

Open the file and modify ports to match the ones allowed:
```
YAML
services:
  zammad-nginx:
    ports:
      - "8080:80"  # Expose Zammad on port 8080
```

Start Zammad
`docker-compose up -d`

Verify Installation:
Open http://<your-ec2-ip>:8080 in your browser (e.g., http://13.211.200.50:8080).
Follow the Zammad setup wizard.
